collections:
  - name: https://github.com/theforeman/foreman-ansible-modules.git
    type: git
  
  - name: https://github.com/theforeman/foreman-operations-collection
    type: git

  - community.general
  - ansible.posix
